spring.application.name=BloggingApp
spring.datasource.url = ${DB_URL}
spring.datasource.username =${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# auto-create/update tables based on entities
spring.jpa.hibernate.ddl-auto=update

# optional: log SQL queries
spring.jpa.show-sql=true
